### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by GitGuy64** [g0T-h/g0thgrabber#1]
i love open sourced. im a lil concerned on gui.py lol, what the heck is with the kernel, whys that needed, or the if user is running as admin.

**Comment by GitGuy64** [comment]
and the self capture screenshot crap. is that like a test grabber or something?

**Comment by GitGuy64** [comment]
i wont download till i know why

**Comment by g0T-h** [comment]
It's open source. Nothing is obfuscated or something like that.

You can ask ChatGPT to explain the code for you.
